{% set name = "grpcio-gcp" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e292605effc7da39b7a8734c719afb12ec4b5362add3528d8afad3aa3aa9057c

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed --verbose

requirements:
  host:
    - python
    - pip >=18.1
    - grpcio-tools >=1.16.1
  run:
    - {{ pin_compatible('grpcio-tools') }}

test:
  imports:
    - grpc_gcp
    - grpc

about:
  home: https://grpc.io
  license: Apache License 2.0
  license_family: APACHE
  summary: 'gRPC extensions for Google Cloud Platform'

  description: |
    gRPC-GCP Python
    ------------

    This repo is created to support GCP specific extensions for gRPC.
    To use the extension features, please refer to grpcio-gcp.

    This repo also contains supporting infrastructures such as
    end2end tests and benchmarks for accessing cloud APIs with gRPC client libraries.

    gRPC-GCP Python is available wherever gRPC is available.

  doc_url: https://grpc.io/docs/
  dev_url: https://github.com/GoogleCloudPlatform/grpc-gcp-python

extra:
  recipe-maintainers:
    - BrentDorsey
